# PyTorch Fundamentals

In [55]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cpu


## Introduction to tensors

### Creating Tensors

PyTorch tensors are created using 'torch.tensor()' - https://pytorch.org/docs/stable/tensors.html

In [56]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [57]:
scalar.ndim

0

In [58]:
scalar.item()

7

In [59]:
vector = torch.tensor([7,7])

In [60]:
vector.ndim

1

In [61]:
vector.shape

torch.Size([2])

In [62]:
# MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [63]:
MATRIX.ndim

2

In [64]:
MATRIX[1]

tensor([ 9, 10])

In [65]:
MATRIX[1][1]

tensor(10)

In [66]:
MATRIX.shape

torch.Size([2, 2])

In [67]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [68]:
TENSOR.ndim

3

In [69]:
TENSOR.shape

torch.Size([1, 3, 3])

torch.Size([4, 3])