# PyTorch Fundamentals

In [94]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cpu


## Introduction to tensors

### Creating Tensors

PyTorch tensors are created using 'torch.tensor()' - https://pytorch.org/docs/stable/tensors.html

In [95]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [96]:
scalar.ndim

0

In [97]:
scalar.item()

7

In [98]:
vector = torch.tensor([7,7])

In [99]:
vector.ndim

1

In [100]:
vector.shape

torch.Size([2])

In [101]:
# MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [102]:
MATRIX.ndim

2

In [103]:
MATRIX[1]

tensor([ 9, 10])

In [104]:
MATRIX[1][1]

tensor(10)

In [105]:
MATRIX.shape

torch.Size([2, 2])

In [106]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [107]:
TENSOR.ndim

3

In [108]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

Why random tensors?

- Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and the adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update numbers -> look at data -> rinse and repeat`

https://pytorch.org/docs/stable/generated/torch.rand.html

In [109]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor



tensor([[0.2435, 0.5732, 0.8208, 0.2242],
        [0.8349, 0.6809, 0.4931, 0.0526],
        [0.4755, 0.5466, 0.1597, 0.0923]])

In [110]:
# Create a random tensor with a similar shape to an image tensor

random_image_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [111]:
my_random_tensor = torch.rand(3,4,5)
my_random_tensor

tensor([[[0.2215, 0.3290, 0.2921, 0.2847, 0.2045],
         [0.0750, 0.8643, 0.8749, 0.8832, 0.7342],
         [0.3329, 0.9707, 0.6201, 0.7155, 0.9222],
         [0.0070, 0.9510, 0.0249, 0.2253, 0.4157]],

        [[0.2639, 0.1423, 0.9324, 0.1021, 0.3786],
         [0.6170, 0.0422, 0.3665, 0.8527, 0.5894],
         [0.6580, 0.4781, 0.5686, 0.0296, 0.4311],
         [0.7075, 0.5008, 0.8297, 0.7607, 0.0084]],

        [[0.0549, 0.3963, 0.3804, 0.1446, 0.1918],
         [0.9006, 0.1249, 0.4315, 0.2148, 0.6651],
         [0.3374, 0.1113, 0.6646, 0.4582, 0.5863],
         [0.7250, 0.2511, 0.9837, 0.3159, 0.8973]]])

### Zeros and ones

In [112]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [113]:
ones = torch.ones(3,4)
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [114]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

https://pytorch.org/docs/stable/generated/torch.arange.html

In [115]:
#use torch.arange()
one_to_ten = torch.arange(start = 1,end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
#creating tensors like

ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [117]:
seven_by_eleven = torch.rand(7,11)
seven_by_eleven

tensor([[0.5676, 0.5901, 0.4902, 0.3139, 0.3417, 0.0690, 0.1012, 0.3695, 0.1857,
         0.9950, 0.3748],
        [0.8248, 0.7216, 0.0882, 0.0077, 0.3137, 0.7700, 0.0526, 0.5750, 0.0133,
         0.5956, 0.2610],
        [0.0035, 0.2812, 0.7395, 0.7647, 0.0614, 0.1133, 0.4981, 0.2699, 0.8340,
         0.0186, 0.9858],
        [0.3923, 0.7757, 0.4986, 0.7248, 0.8950, 0.0732, 0.0688, 0.1360, 0.4717,
         0.8397, 0.7515],
        [0.8245, 0.3319, 0.7414, 0.6585, 0.1931, 0.2350, 0.9938, 0.4086, 0.3106,
         0.9768, 0.2435],
        [0.6782, 0.5227, 0.8116, 0.6333, 0.4749, 0.8014, 0.9701, 0.2156, 0.2504,
         0.2122, 0.1684],
        [0.5173, 0.0723, 0.8082, 0.8249, 0.6607, 0.4097, 0.0540, 0.0106, 0.1506,
         0.0571, 0.7213]])

In [118]:
seven_zeroes = torch.zeros_like(seven_by_eleven)
seven_zeroes

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])