# PyTorch Fundamentals

In [268]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cpu


## Introduction to tensors

### Creating Tensors

PyTorch tensors are created using 'torch.tensor()' - https://pytorch.org/docs/stable/tensors.html

In [269]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [270]:
scalar.ndim

0

In [271]:
scalar.item()

7

In [272]:
vector = torch.tensor([7,7])

In [273]:
vector.ndim

1

In [274]:
vector.shape

torch.Size([2])

In [275]:
# MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [276]:
MATRIX.ndim

2

In [277]:
MATRIX[1]

tensor([ 9, 10])

In [278]:
MATRIX[1][1]

tensor(10)

In [279]:
MATRIX.shape

torch.Size([2, 2])

In [280]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [281]:
TENSOR.ndim

3

In [282]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

Why random tensors?

- Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and the adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update numbers -> look at data -> rinse and repeat`

https://pytorch.org/docs/stable/generated/torch.rand.html

In [283]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor



tensor([[0.9486, 0.2980, 0.1714, 0.5682],
        [0.7878, 0.0140, 0.9757, 0.8373],
        [0.3919, 0.5893, 0.6860, 0.4697]])

In [284]:
# Create a random tensor with a similar shape to an image tensor

random_image_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [285]:
my_random_tensor = torch.rand(3,4,5)
my_random_tensor

tensor([[[0.0582, 0.6843, 0.9002, 0.5194, 0.7392],
         [0.5526, 0.2068, 0.9482, 0.3024, 0.4714],
         [0.8278, 0.2993, 0.2463, 0.1461, 0.7123],
         [0.9782, 0.5816, 0.0116, 0.5123, 0.0170]],

        [[0.5138, 0.3021, 0.4755, 0.3263, 0.0845],
         [0.0946, 0.9178, 0.1471, 0.5629, 0.5930],
         [0.8995, 0.2348, 0.8226, 0.0330, 0.4364],
         [0.1195, 0.7778, 0.5873, 0.5358, 0.0930]],

        [[0.8647, 0.4959, 0.1972, 0.9753, 0.7091],
         [0.5010, 0.8218, 0.2826, 0.0562, 0.7175],
         [0.6150, 0.7365, 0.0640, 0.8418, 0.2915],
         [0.9674, 0.0603, 0.3047, 0.3519, 0.1099]]])

### Zeros and ones

In [286]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [287]:
ones = torch.ones(3,4)
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [288]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

https://pytorch.org/docs/stable/generated/torch.arange.html

In [289]:
#use torch.arange()
one_to_ten = torch.arange(start = 1,end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [290]:
#creating tensors like

ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [291]:
seven_by_eleven = torch.rand(7,11)
seven_by_eleven

tensor([[4.1085e-01, 3.8714e-01, 2.5782e-01, 6.1240e-01, 5.4044e-01, 6.5035e-01,
         3.3868e-02, 5.0681e-01, 8.1989e-01, 3.7717e-01, 9.3077e-01],
        [3.3924e-01, 6.9465e-01, 1.9842e-01, 3.2329e-02, 2.7398e-01, 5.8580e-01,
         2.7395e-01, 3.3356e-02, 2.8830e-01, 5.4639e-01, 9.9970e-01],
        [2.3370e-01, 5.1975e-01, 7.2834e-01, 8.2799e-01, 8.8009e-01, 7.6028e-01,
         1.1652e-01, 9.8159e-01, 1.5528e-01, 1.0583e-01, 5.7674e-01],
        [1.3441e-01, 8.8971e-01, 8.9249e-01, 7.8065e-01, 6.5838e-01, 4.5058e-01,
         9.3967e-01, 4.3035e-01, 3.6335e-01, 8.0389e-02, 5.8857e-03],
        [7.4565e-04, 3.9796e-01, 2.5103e-01, 3.9061e-02, 8.3008e-01, 7.2408e-01,
         7.8887e-01, 6.8877e-01, 2.7553e-01, 7.4690e-01, 6.7007e-01],
        [5.5416e-01, 2.0198e-01, 2.9502e-02, 4.5057e-01, 6.5051e-01, 4.0608e-01,
         2.0664e-01, 3.3738e-01, 7.2515e-01, 5.2626e-01, 9.0547e-01],
        [4.6999e-01, 6.0125e-01, 2.0838e-01, 7.2511e-01, 9.8914e-01, 6.2437e-01,
         1.64

In [292]:
seven_zeroes = torch.zeros_like(seven_by_eleven)
seven_zeroes

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big error one runs into with PyTorch & deep learning:
1. Tensors not right datatype
2. tensors not right shape
3. tensors not on the right device

In [293]:
# Float 32 tensor

float_32_tensor = torch.tensor(
    [3.0,6.0,9.0],
    dtype=None, # what data type is the tensor
    device=None, # where to store the tensor (CPU or GPU)
    requires_grad=False # whether to keep track of the gradients for this tensors operations
    )
float_32_tensor

tensor([3., 6., 9.])

In [294]:
float_32_tensor.dtype

torch.float32

In [295]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [296]:
multiplication_float = float_16_tensor*float_32_tensor
multiplication_float.dtype

torch.float32

In [297]:
float_64_tensor = float_32_tensor.type(torch.float64)
multiplication_float = float_64_tensor*float_16_tensor*float_32_tensor

multiplication_float

tensor([ 27., 216., 729.], dtype=torch.float64)

### Getting information from tensors
1. Tensors not right datatype - To get datatype from tensor can user 'tensor.dtype'
2. tensors not right shape - to get shape can use 'tensor.shape'
3. tensors not on the right device - to get device can use 'tensor.device'

In [298]:
# Create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1525, 0.6435, 0.5466, 0.2257],
        [0.6533, 0.8078, 0.7704, 0.2921],
        [0.5783, 0.6653, 0.4617, 0.0835]])

In [299]:
# find detail about tensor

print(f'dimensions of tensor: {some_tensor.ndim}'.title())
print(f'shape of tensor: {some_tensor.shape}'.title())
print(f'type of tensor: {some_tensor.dtype}'.title())
print(f'device of tensor: {some_tensor.device}'.title())

Dimensions Of Tensor: 2
Shape Of Tensor: Torch.Size([3, 4])
Type Of Tensor: Torch.Float32
Device Of Tensor: Cpu


In [300]:
#cuda not available

torch.cuda.is_available()

False

### Manipulating tensors (tensor operations)

#### Tensor operations include:
- Addition
- Substraction
- Multiplication(element-wise)
- Division
- Matrix Multiplication

In [301]:
# Create a tensor
tensor = torch.tensor([1,2,3])

#Add 10 to each element
tensor += 10
tensor

tensor([11, 12, 13])

In [302]:
# Multiply each element by 10
tensor *= 10
tensor

tensor([110, 120, 130])

In [303]:
# subtract 10 from each element
tensor = torch.tensor([1,2,3])
tensor -= 10
tensor

tensor([-9, -8, -7])